# Generated by Django 3.2.5 on 2021-07-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='ISO2',
        ),
        migrations.RemoveField(
            model_name='area',
            name='ISO3',
        ),
        migrations.AlterField(
            model_name='globalgenerationannual',
            name='area',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='globalgenerationannual',
            name='fueltype',
            field=models.CharField(max_length=255),
        ),
    ]
