# Generated by Django 3.2.5 on 2021-07-21 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210721_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalgenerationannual',
            name='generation_twh',
            field=models.FloatField(default=None, null=True),
        ),
    ]
