# Generated by Django 3.2.5 on 2021-07-21 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_globalgenerationannual_generation_twh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalgenerationannual',
            name='generation_twh',
            field=models.FloatField(default=None),
        ),
    ]
